import Login from './Login'
import Notification from './Notification'
import About from './About'
import Home from './Home'
import NotFoundPage from './Error/notfoundpage'
import Register from './Register'
import Booking from './Booking'
import Schedule from './Schedule'
import CustomerList from './CustomerList'
import PaymentList from './PaymentList'
import AirportList from './AirportList'
import TicketList from './TicketList'
import Wishlist from './Wishlist'
import UserList from './UserList'
import Profile  from './Profile'
import Checkout from './Checkout'
import TicketPromo from './TicketPromo'

export { Login, Notification, NotFoundPage, About, Home, Register, Schedule, Booking, CustomerList, PaymentList, Profile, Checkout, Wishlist, AirportList, TicketList, UserList, TicketPromo }