import Login from './Login'
import Notification from './Notification'
import About from './About'
import Home from './Home'
import NotFoundPage from './Error/notfoundpage'
import Register from './Register'
import Booking from './Booking'
import Schedule from './Schedule'
import CustomerList from './CustomerList'
import AirportList from './AirportList'
import TicketList from './TicketList'
import Wishlist from './Wishlist'
import UserList from './UserList'
import Profile  from './Profile'
import Checkout from './Checkout'
import TicketPromo from './TicketPromo'
import ProtectedAdmin from './ProtectedAdmin'
import ProtectedUser from './ProtectedUser'
import SearchTicket from './SearchTicket'
import History from './History'

export { Login, Notification, NotFoundPage, About, Home, Register, Schedule, Booking, CustomerList, Profile, Checkout, Wishlist, AirportList, TicketList, UserList, TicketPromo, ProtectedAdmin, ProtectedUser, SearchTicket, History }